export const state = {
    gameState: 'MENU', 
    currentForm: 'beachBall', 
    isSinking: false,
    sinkTarget: null,
    isPaused: false, 
    playerName: "Player",
    survivalTime: 0,
    pinsSmashed: 0,
    distanceTraveled: 0,
    gameOverTimer: 0,
    gatesPassed: 0, 
    gameElapsedTime: 0, 
    nextSpawnZ: -40, 
    nextGateZ: -1000, 
    wasGap: false,
    activePowerUp: null,
    powerUpTimer: 0,
    currentLane: 0, 
    baseSpeed: -22, 
    forwardSpeed: -22,
    currentStageIdx: 0,
    trackStageIdx: 0,
    oldStageIdx: 0,
    transitionProgress: 1.0,
    highScore: { score: 0, time: 0, distance: 0, pins: 0, player: "" },
    currentScore: 0,
    hasReachedNewHighScore: false,
    isTransitioning: false
};

export const pools = {
    powerups: [],
    windParticles: [],
    sceneryParticles: [],
    floorParticles: [],
    trackTiles: [],
    obstacles: [],
    puddles: [],
    debrisList: [],
    gates: [],
    sceneryList: [],
    splashParticles: []
};